Using /Users/mahijazi/opensource/homelab/ansible.cfg as config file

PLAY [Install Pi-hole] *********************************************************

TASK [Gathering Facts] *********************************************************
ok: [link]

TASK [Ensure Pi-hole configuration directory exists] ***************************
ok: [link] => {
    "changed": false,
    "gid": 0,
    "group": "root",
    "mode": "0755",
    "owner": "root",
    "path": "/etc/pihole",
    "size": 4096,
    "state": "directory",
    "uid": 0
}

TASK [Configure Pi-hole installation variables] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [link]: FAILED! => {
    "changed": false
}

MSG:

Could not find or access 'templates/pihole.setupvars.j2'
Searched in:
	/Users/mahijazi/opensource/homelab/playbooks/templates/templates/pihole.setupvars.j2
	/Users/mahijazi/opensource/homelab/playbooks/templates/pihole.setupvars.j2
	/Users/mahijazi/opensource/homelab/playbooks/templates/templates/pihole.setupvars.j2
	/Users/mahijazi/opensource/homelab/playbooks/templates/pihole.setupvars.j2 on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

PLAY RECAP *********************************************************************
link                       : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

